---
title             : "Lab 8"
shorttitle        : "The papaja file for lab 8"

author: 
  - name          : "Lisa Strycker"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Eugene, OR"
    email         : "lisas@ori.org"
  - name          : "Lisa Strycker"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Oregon Research Institute"
  - id            : "2"
    institution   : "University of Oregon"

abstract: |
  ANimal species have different behaviors for avoiding predators. Tonic immobility of a form of passive anti-predator behavior.
  
  In tonic immobility, organisms do not respond to external stimulation.
  
  Tonic immobility has been shown in isopods, including "sow bugs," but is largely unstudied. This study answered four research questions: (a) Do species differ in responsiveness to tonic immobility-inducing stimuli? (b) Does the responsiveness depend upon sex, size, or stimulus? (c) Is the duration of tonic immobility influenced by sex, size, or type of stimulus, and does it differ between species? (d) Is the duration of tonic immobility related to the time needed to elicit a response?
  
  Here we show that responses to external stimuli differ within and between three species of isopods. Three distinct patterns were found.
  
  Relatively stronger responses to different stimuli (e.g., drop, touch) may be because some species tend to have visual predators that are larger or smaller than they are. 
  
  More studies are needed to investigative whether anti-predator strategies like tonic immobility improve survivorship.
  
  Future research should elucidate which responses work for different predators.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "tonic immobility"
wordcount         : no

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
